[env]
LIBTORCH = { value = "/usr/local/lib/libtorch" , relative = true }
DYLD_LIBRARY_PATH = { value = "/usr/local/lib/libtorch/lib" , relative = true }

[profile.dev]
opt-level=3


[profile.release]
debug = true

[profile.bench]
debug = true